"""empty message

Revision ID: 3d5aad4987de
Revises: 7c57a918ab49
Create Date: 2023-12-03 17:45:49.639347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5aad4987de'
down_revision = '7c57a918ab49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('received_by', sa.String(length=50), nullable=True))
        batch_op.drop_column('receiver_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_by', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('received_by')

    # ### end Alembic commands ###
