"""empty message

Revision ID: 7c57a918ab49
Revises: 7d0542b340db
Create Date: 2023-12-03 16:42:56.297721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c57a918ab49'
down_revision = '7d0542b340db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waybill_log',
    sa.Column('wid', sa.Integer(), nullable=False),
    sa.Column('waybill_number', sa.String(length=50), nullable=True),
    sa.Column('haulier_ref', sa.String(length=50), nullable=True),
    sa.Column('customer_ref', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('haulier_id', sa.Integer(), nullable=True),
    sa.Column('weight_log_id', sa.Integer(), nullable=True),
    sa.Column('delivery_address', sa.String(length=120), nullable=True),
    sa.Column('product_info', sa.String(length=650), nullable=True),
    sa.Column('product_condition', sa.String(length=50), nullable=True),
    sa.Column('bad_product_info', sa.String(length=650), nullable=True),
    sa.Column('file_link', sa.String(length=650), nullable=True),
    sa.Column('receiver_by', sa.String(length=50), nullable=True),
    sa.Column('delivered_by', sa.String(length=50), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('approval_time', sa.DateTime(), nullable=True),
    sa.Column('reg_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.cid'], ),
    sa.ForeignKeyConstraint(['haulier_id'], ['transport_company.hid'], ),
    sa.PrimaryKeyConstraint('wid')
    )
    op.drop_table('waybill')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waybill',
    sa.Column('wid', sa.INTEGER(), nullable=False),
    sa.Column('waybill_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('company_ref', sa.VARCHAR(length=50), nullable=True),
    sa.Column('customer_ref', sa.VARCHAR(length=50), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('report_id', sa.INTEGER(), nullable=True),
    sa.Column('weight_log_id', sa.INTEGER(), nullable=True),
    sa.Column('delivery_address', sa.VARCHAR(length=120), nullable=True),
    sa.Column('product_description', sa.VARCHAR(length=120), nullable=True),
    sa.Column('item_code', sa.VARCHAR(length=120), nullable=True),
    sa.Column('product_count', sa.INTEGER(), nullable=True),
    sa.Column('product_weight', sa.INTEGER(), nullable=True),
    sa.Column('accepted_qty', sa.INTEGER(), nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=120), nullable=True),
    sa.Column('waybill_time', sa.DATETIME(), nullable=True),
    sa.Column('product_condition', sa.VARCHAR(length=50), nullable=True),
    sa.Column('damaged_qty', sa.INTEGER(), nullable=True),
    sa.Column('shortage', sa.INTEGER(), nullable=True),
    sa.Column('batch_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('receiver_by', sa.VARCHAR(length=50), nullable=True),
    sa.Column('delivered_by', sa.VARCHAR(length=50), nullable=True),
    sa.Column('primary_approval', sa.VARCHAR(length=50), nullable=True),
    sa.Column('p_time', sa.DATETIME(), nullable=True),
    sa.Column('secondary_approval', sa.VARCHAR(length=50), nullable=True),
    sa.Column('s_time', sa.DATETIME(), nullable=True),
    sa.Column('tertiary_approval', sa.VARCHAR(length=50), nullable=True),
    sa.Column('t_time', sa.DATETIME(), nullable=True),
    sa.Column('reg_date', sa.DATETIME(), nullable=True),
    sa.Column('file_link', sa.VARCHAR(length=650), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.cid'], ),
    sa.PrimaryKeyConstraint('wid')
    )
    op.drop_table('waybill_log')
    # ### end Alembic commands ###
