"""empty message

Revision ID: 7d0542b340db
Revises: 
Create Date: 2023-11-30 02:42:51.854201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0542b340db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_link', sa.String(length=650), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill', schema=None) as batch_op:
        batch_op.drop_column('file_link')

    # ### end Alembic commands ###
