"""empty message

Revision ID: b67a0fa8660e
Revises: 3d5aad4987de
Create Date: 2023-12-31 23:50:24.550538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67a0fa8660e'
down_revision = '3d5aad4987de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_flag', sa.Integer(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_flag', sa.Integer(), nullable=True))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_flag', sa.Integer(), nullable=True))

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_flag', sa.Integer(), nullable=True))

    with op.batch_alter_table('transport_company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_flag', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_flag', sa.Integer(), nullable=True))

    with op.batch_alter_table('waybill_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_flag', sa.Integer(), nullable=True))

    with op.batch_alter_table('weight_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_flag', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_log', schema=None) as batch_op:
        batch_op.drop_column('delete_flag')

    with op.batch_alter_table('waybill_log', schema=None) as batch_op:
        batch_op.drop_column('delete_flag')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('delete_flag')

    with op.batch_alter_table('transport_company', schema=None) as batch_op:
        batch_op.drop_column('delete_flag')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('delete_flag')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('delete_flag')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('delete_flag')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('delete_flag')

    # ### end Alembic commands ###
